version: '3'
services:
  backend:
    build: 
      context: ./backend/
    image: touch-typing-backend
    container_name: touch-typing-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./backend/src/:/app/src/"
  database:
    image: mysql #oficial dockerhub image
    container_name: touch-typing-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
